#!/usr/bin/env python3
"""Inline route_scan.py into every copy of the Claude Security workflow.

The workflow runs as an org *required workflow*, injected into repos that hold no file
of their own, so it cannot read a sibling script from this repository -- and a public
repo could not authenticate a cross-repo checkout of this internal one either. The
router therefore has to travel inside the YAML. This script is what makes that safe:
route_scan.py stays the single canonical, unit-tested source, and the embedded copies
are generated from it.

  python3 security-router/embed.py            # rewrite the embedded copies
  python3 security-router/embed.py --check    # fail if any copy has drifted (CI)

Targets outside this repository (the committed copies in public repos) are passed
explicitly with --target.
"""
import argparse, os, re, sys, tempfile

BEGIN = "# >>> BEGIN security-router/route_scan.py -- generated by security-router/embed.py; edit that file, not this block >>>"
END = "# <<< END security-router/route_scan.py <<<"

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCE = os.path.join(HERE, "route_scan.py")
TRIVY = os.path.join(HERE, "trivy_contract.py")
TRIVY_BEGIN = BEGIN.replace("route_scan.py", "trivy_contract.py")
TRIVY_END = END.replace("route_scan.py", "trivy_contract.py")
MARKERS = {BEGIN, END, TRIVY_BEGIN, TRIVY_END}
DEFAULT_TARGETS = [os.path.join(os.path.dirname(HERE), ".github", "workflows", "pr-security-gate.yml")]


def render(source_text, indent, sentinels, begin=BEGIN, end=END):
    """Inline the source, refusing anything that could break out of the heredoc.

    The embedded block lives inside `python3 - ... <<'SENTINEL'`, and YAML block-scalar
    de-indentation puts every rendered line back at column zero. So a source line that is
    exactly the sentinel ENDS the heredoc, and every line after it is executed by bash --
    in a step holding `pull-requests: write`, `id-token: write` and a checkout credential,
    on every PR in the org. A Python string or comment containing that word on its own line
    is enough, which passes both `py_compile` and the unit tests, and reviewers are told not
    to read the generated block. Refuse at generation time instead.

    `sentinels` is every quoted delimiter in the target file, so the check cannot be
    redirected at a different block's name.
    """
    if isinstance(sentinels, str):
        sentinels = {sentinels}
    for n, line in enumerate(source_text.splitlines(), 1):
        stripped = line.strip()
        if stripped in sentinels:
            raise SystemExit(
                "route_scan.py:%d is exactly the heredoc sentinel %r, which would terminate\n"
                "the heredoc and hand the remaining lines to bash. Rename or reword the line."
                % (n, stripped)
            )
        if stripped in MARKERS:
            raise SystemExit(
                "route_scan.py:%d duplicates an embed marker, which would corrupt the splice."
                % n
            )

    pad = " " * indent
    lines = [pad + begin]
    for line in source_text.splitlines():
        # A blank line stays blank: trailing whitespace in a YAML block scalar is
        # preserved and would show up as noise in the rendered script.
        lines.append(pad + line if line.strip() else "")
    lines.append(pad + end)
    return "\n".join(lines)


def splice(path, source_text, begin=BEGIN, end=END):
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    lines = text.split("\n")

    starts = [i for i, l in enumerate(lines) if l.strip() == begin]
    ends = [i for i, l in enumerate(lines) if l.strip() == end]
    if len(starts) != 1 or len(ends) != 1 or ends[0] < starts[0]:
        raise SystemExit(
            "%s: expected exactly one BEGIN/END router marker pair (found %d/%d).\n"
            "Add these two lines inside the router step's `run: |` block, at the block's\n"
            "own indentation, and re-run:\n  %s\n  %s"
            % (path, len(starts), len(ends), begin, end)
        )

    indent = len(lines[starts[0]]) - len(lines[starts[0]].lstrip())

    # Collect EVERY quoted heredoc delimiter in the file, not just the nearest one above the
    # marker. Scanning backwards for the closest match is spoofable: one innocuous comment
    # above the BEGIN marker mentioning another block's delimiter -- say
    # `# (the gate step uses a similar <<'GATE_PY' block)` -- silently retargets the guard, so
    # the real sentinel is never checked and the escape reopens. Two individually harmless
    # diffs, which is more review-resistant than the single-diff version. Checking all of them
    # costs nothing and cannot be redirected.
    sentinels = set(re.findall(r"<<-?'([A-Za-z_][A-Za-z0-9_]*)'", text))
    if not sentinels:
        raise SystemExit(
            "%s: could not find a quoted heredoc delimiter anywhere in the file." % path
        )

    rendered = render(source_text, indent, sentinels, begin, end)
    updated = "\n".join(lines[: starts[0]] + rendered.split("\n") + lines[ends[0] + 1 :])
    return text, updated


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report drift instead of rewriting")
    ap.add_argument("--target", action="append", default=[], help="extra workflow copy to sync")
    args = ap.parse_args()

    with open(SOURCE, encoding="utf-8") as fh:
        source_text = fh.read()

    targets = DEFAULT_TARGETS + args.target
    drifted = []
    for path in targets:
        if not os.path.exists(path):
            print("skip   %s (not present)" % path)
            continue
        before, after = splice(path, source_text)
        # Validate both sources before writing anything. All quoted delimiters
        # and both marker pairs are protected, regardless of source name.
        with tempfile.TemporaryDirectory() as temporary:
            draft = os.path.join(temporary, "workflow.yml")
            with open(draft, "w", encoding="utf-8") as fh:
                fh.write(after)
            with open(TRIVY, encoding="utf-8") as fh:
                _, after = splice(draft, fh.read(), TRIVY_BEGIN, TRIVY_END)
        if before == after:
            print("ok     %s" % path)
            continue
        drifted.append(path)
        if args.check:
            print("DRIFT  %s" % path)
        else:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(after)
            print("update %s" % path)

    if args.check and drifted:
        print(
            "\n%d workflow cop%s out of sync with security-router/route_scan.py.\n"
            "Run: python3 security-router/embed.py" % (len(drifted), "y is" if len(drifted) == 1 else "ies are")
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
